In [1]:
import numpy as np

In [2]:
x = [1,2,4,6,9,3]

In [3]:
y = [4,6,5,3,1]

In [6]:
np.save('testx.npy',x)

In [7]:
loadx = np.load('testx.npy')
loadx

array([1, 2, 4, 6, 9, 3])

In [8]:
# to save multiple files use savez and .npz
np.savez('testxy.npz',x=x,y=y)

In [9]:
loadxy = np.load('testxy.npz')
loadxy

In [14]:
loadxy['x']

array([1, 2, 4, 6, 9, 3])

In [15]:
loadxy['y']

array([4, 6, 5, 3, 1])