In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,5,7])

In [3]:
x[4]

7

In [4]:
x>5

array([False, False, False, False,  True])

In [5]:
x[x>5]      # boolean indexing

array([7])

In [6]:
#fancy indexing
x[[2,1]]

array([3, 2])

In [7]:
#slicing
x = np.random.randn(10,10)

In [8]:
x

array([[ 1.04368772, -0.40642585, -0.91323189, -0.68086713, -0.32474583,
        -0.52899747, -0.75864574, -0.87549932, -0.24376243,  0.47122849],
       [-0.85940731,  1.0340649 ,  0.25671156,  0.85950885,  0.67485059,
         0.76707854,  1.3817183 ,  0.47177593, -1.71653746, -1.56932182],
       [-1.68571943,  0.61699993,  0.5652763 , -0.10185051, -0.25576895,
         0.62646561, -0.38654026, -0.56861591, -0.16799897,  0.49661999],
       [ 0.57057312, -0.33892543,  1.16819397, -0.12066376, -0.3760015 ,
        -0.68388355, -0.14129536,  0.75183614, -1.23010052,  0.31214898],
       [-0.20197296,  0.83397815, -1.57390908,  0.14280119,  0.71042074,
        -1.20390405,  1.14301216, -0.82362514, -0.36042052, -0.49755047],
       [ 0.06661609, -0.03456654,  0.58256946,  0.13552698,  1.30016718,
         1.11015456,  1.32633721, -0.77047972,  0.00680111, -0.45974325],
       [ 1.00079353,  0.01287839,  1.28494385,  0.02134999, -0.76212588,
         0.97402225,  0.12783605, -0.60992693

In [9]:
# for first row
x[0]

array([ 1.04368772, -0.40642585, -0.91323189, -0.68086713, -0.32474583,
       -0.52899747, -0.75864574, -0.87549932, -0.24376243,  0.47122849])

In [10]:
# first row and fifth column
x[0][5]

-0.5289974652113741

In [11]:
# if we need from first row to tenth row but every odd row, and all columns

x[1:10:2,::] # to get all columns we can skip the  :: sign 

array([[-0.85940731,  1.0340649 ,  0.25671156,  0.85950885,  0.67485059,
         0.76707854,  1.3817183 ,  0.47177593, -1.71653746, -1.56932182],
       [ 0.57057312, -0.33892543,  1.16819397, -0.12066376, -0.3760015 ,
        -0.68388355, -0.14129536,  0.75183614, -1.23010052,  0.31214898],
       [ 0.06661609, -0.03456654,  0.58256946,  0.13552698,  1.30016718,
         1.11015456,  1.32633721, -0.77047972,  0.00680111, -0.45974325],
       [-0.96127772, -0.28315384, -0.13429177, -0.47841588, -0.09289645,
        -1.40470819,  0.64338904,  0.83675599, -0.77346169,  0.30620569],
       [-0.68815515, -1.2004013 , -0.51378584, -0.60030048,  0.22691763,
        -0.94373585,  0.18268286,  0.96719864,  0.93442008, -1.24645636]])

In [12]:
# for all rows and first four columns
x[::,0:4] # for accesing all rows we have to write :: 

array([[ 1.04368772, -0.40642585, -0.91323189, -0.68086713],
       [-0.85940731,  1.0340649 ,  0.25671156,  0.85950885],
       [-1.68571943,  0.61699993,  0.5652763 , -0.10185051],
       [ 0.57057312, -0.33892543,  1.16819397, -0.12066376],
       [-0.20197296,  0.83397815, -1.57390908,  0.14280119],
       [ 0.06661609, -0.03456654,  0.58256946,  0.13552698],
       [ 1.00079353,  0.01287839,  1.28494385,  0.02134999],
       [-0.96127772, -0.28315384, -0.13429177, -0.47841588],
       [-1.24624791, -1.97128312,  1.13802328, -0.21436613],
       [-0.68815515, -1.2004013 , -0.51378584, -0.60030048]])

In [13]:
#lets make a square in which border values are 1 and inside are zeros

In [15]:
a = np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
a[1:-1,1:-1]=0

In [19]:
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])