In [1]:
import numpy as np

In [3]:
x = np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
#to create numpy array from list

l = [1,4,5,7]

In [5]:
np.array(l)

array([1, 4, 5, 7])

In [6]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])